# Generated by Django 5.1.4 on 2025-05-21 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='category',
            field=models.CharField(blank=True, help_text='Catégorie de la conversation', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Épingler la conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='message_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, help_text='Résumé automatique de la conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Liste des tags associés à la conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='content_type',
            field=models.CharField(default='text', help_text='Type de contenu (text, code, markdown...)', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Métadonnées techniques (tokens, temps de réponse...)'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Reçu'), ('error', 'Erreur')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, help_text='Données structurées additionnelles'),
        ),
        migrations.AlterField(
            model_name='message',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, help_text='Données structurées additionnelles (code, citations...)'),
        ),
    ]
